import fs from "node:fs/promises";
import path from "node:path";
import { updateSmsPlan } from "./smsPremium.js";
const DATA_DIR = process.env.DATA_DIR || "/data/gold-alert-pro";
const FILE = path.join(DATA_DIR, "commerce-settings.json");
const defaults = { cardNumber: process.env.PAYMENT_CARD_NUMBER || "", cardHolder: process.env.PAYMENT_CARD_HOLDER || "", subscriptionPriceIRR: Number(process.env.SMS_PLAN_PRICE_IRR || 5000000), subscriptionDays: Number(process.env.SMS_PLAN_DAYS || 30), subscriptionLabel: "SMS Premium" };
let current = { ...defaults }; let loaded = false;
export async function getCommerceSettings() { if (!loaded) { loaded = true; try { const x=JSON.parse(await fs.readFile(FILE,"utf8")); current={...defaults,...x}; } catch {} updateSmsPlan({priceIRR:current.subscriptionPriceIRR,days:current.subscriptionDays}); } return { ...current }; }
export async function setCommerceSettings(input={}) { await getCommerceSettings(); const cardNumber=String(input.cardNumber??current.cardNumber).replace(/[^0-9 -]/g,"").slice(0,32); const cardHolder=String(input.cardHolder??current.cardHolder).trim().slice(0,100); const subscriptionLabel=String(input.subscriptionLabel??current.subscriptionLabel).trim().slice(0,60)||"SMS Premium"; const subscriptionPriceIRR=Number(input.subscriptionPriceIRR??current.subscriptionPriceIRR); const subscriptionDays=Number(input.subscriptionDays??current.subscriptionDays); if(!Number.isSafeInteger(subscriptionPriceIRR)||subscriptionPriceIRR<0||subscriptionPriceIRR>100000000000) throw new Error("مبلغ اشتراک نامعتبر است."); if(!Number.isInteger(subscriptionDays)||subscriptionDays<1||subscriptionDays>3650) throw new Error("مدت اشتراک باید بین ۱ تا ۳۶۵۰ روز باشد."); current={cardNumber,cardHolder,subscriptionLabel,subscriptionPriceIRR,subscriptionDays}; updateSmsPlan({priceIRR:subscriptionPriceIRR,days:subscriptionDays}); await fs.mkdir(DATA_DIR,{recursive:true}); const tmp=FILE+".tmp"; await fs.writeFile(tmp,JSON.stringify(current,null,2),"utf8"); await fs.rename(tmp,FILE); return {...current}; }
